
//Création d'un wilder
POST http://localhost:3000/api/wilder
Content-Type: application/json

{
    "name": "Louis"
}

###

//Lire tout les wilder
GET http://localhost:3000/api/wilder?nameContains=to


###

//Modifier un wilder
PATCH http://localhost:3000/api/wilder/4
Content-Type: application/json

{
    "name": "Super"
}


###

//Supprimer un wilder
DELETE http://localhost:3000/api/wilder/5
Content-Type: application/json